security:
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            entity: { class: AppBundle\Entity\User, property: username }
 
    encoders:
        AppBundle\Entity\User: bcrypt
        
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login
            logout: { path: /logout, target: / }
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                #always_remember_me: true
                    
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/adverts/*, roles: ROLE_USER }